#!/bin/bash

function getOps() {
	echo Assign cases to option flags
}

function isRecyclebin() {
	recyclePath="$HOME/recyclebin"
	if [[ ! -d $recyclePath ]]
	then
		echo Recyclebin not found.
		mkdir $recyclePath
		echo Created recyclebin at $recyclePath
	fi
}

function getName() {
	fileName=$(basename $1)
	folderPath=$(dirname $1)
}

function isFile() {
	if [[ -z $1 ]]
	then
		echo Please input file name
	elif [[ -d $1 ]]
	then
		echo Directory not allowed
	else
		if [[ ! -f $1 ]]
		then
			echo File does not exists
		fi
	fi

}

function isAllowedfile() {
	if [[ $folderPath = "$HOME/project" ]]
	then
		if [[ $fileName = "recycle" || $fileName = "restore" ]]
		then
			echo File not allowed to be removed.
		fi
	fi

	if [[ $folderPath = $HOME && $fileName = ".restore.info" ]]
	then
		echo File not allowed to be removed.
	fi
}
# function to check file permissions?
function recycleFile() {
	inode=$(ls -i $1 | cut -d" " -f1)
	outputPath="$recyclePath/$fileName"_"$inode"
	cp $1 $outputPath # copy file to recyclebin, rename to fileName_inode
	rm $1 # remove input file
}

function isLog() {
	logPath="$HOME/.restore.info"
	if [[ ! -f $logPath ]]
	then
		touch $logPath
	fi	
}

function logProcess() {
	echo Log original absolution file path and file name in recyclebin to .restore.info
}

function errorMessage() {
	echo Display error messages
}

###############		MAIN	#################

#getOps
shift $(($OPTIND - 1))
isRecyclebin
isLog
isFile $*
getName $*
isAllowedfile
recycleFile $*
#logProcess
#errorMessage
